
export enum ROLES {
    ADMIN = "ADMIN",
    COMPANY = "COMPANY", 
    CUSTOMER = "CUSTOMER"
}

export enum CATEGORIES {
    FOOD = "FOOD",
    ELECTRICITY = "ELECTRICITY",
    RESTAURANT = "RESTAURANT", 
    VACATION = "VACATION"
}